# Generated by Django 5.2.6 on 2025-09-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='e-mail')),
                ('hash_password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('created_at', models.DateTimeField(verbose_name='Дата и время регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['surname', 'name'],
                'indexes': [models.Index(fields=['surname'], name='gagi_app_us_surname_12b928_idx')],
                'constraints': [models.UniqueConstraint(fields=('surname', 'email'), name='unique_surname_email')],
            },
        ),
    ]
