# Generated by Django 5.2.6 on 2025-09-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gagi_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Author',
        ),
    ]
