# Generated by Django 5.2.6 on 2025-09-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gagi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('passport', models.CharField(max_length=13, unique=True, verbose_name='Паспорт')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['name', 'surname', 'position'],
                'indexes': [models.Index(fields=['position'], name='gagi_app_st_positio_4d3671_idx')],
                'constraints': [models.UniqueConstraint(fields=('surname', 'passport'), name='unique_surname_passport')],
            },
        ),
    ]
