# Generated by Django 5.2.6 on 2025-09-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gagi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='e-mail'),
        ),
    ]
