# Generated by Django 5.2.6 on 2025-09-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gagi_app', '0002_rename_autor_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname', 'name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Автор'},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='surnabe',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='author',
            name='desc',
            field=models.CharField(default='No', verbose_name='Умер или нет'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['surname'], name='gagi_app_au_surname_0a6276_idx'),
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(condition=models.Q(('desc', 'Жив')), fields=('surname', 'bio'), name='unique_surname_bio'),
        ),
    ]
