# Generated by Django 5.2.6 on 2025-10-01 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gagi_app', '0002_alter_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('actual_duration', models.IntegerField(blank=True, null=True, verbose_name='Фактическая продолжительность (сек)')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('delayed', 'Задержано')], default='pending', max_length=20, verbose_name='Статус')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gagi_app.attractions', verbose_name='Аттракцион')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gagi_app.staff', verbose_name='Сотрудник')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gagi_app.tickets', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Сеанс аттракциона',
                'verbose_name_plural': 'Сеансы аттракционов',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['attraction', 'start_time'], name='gagi_app_si_attract_12c2b4_idx'), models.Index(fields=['status'], name='gagi_app_si_status_070bc9_idx')],
            },
        ),
    ]
