# Generated by Django 5.2.6 on 2025-09-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gagi_app', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('min_height', models.IntegerField(verbose_name='Минимальный рост')),
                ('max_height', models.IntegerField(verbose_name='Максимальный рост')),
                ('min_age', models.IntegerField(verbose_name='Минимальный возраст')),
                ('activity_status', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('duration_seconds', models.IntegerField(verbose_name='Продолжительность (сек)')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gagi_app.staff', verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Аттракцион',
                'verbose_name_plural': 'Аттракционы',
                'ordering': ['name'],
            },
        ),
    ]
