# Generated by Django 5.2.6 on 2025-09-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gagi_app', '0003_attractions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('validity_duration', models.IntegerField(verbose_name='Срок действия (дни)')),
            ],
            options={
                'verbose_name': 'Тип билета',
                'verbose_name_plural': 'Типы билетов',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='attractions',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='e-mail'),
        ),
        migrations.AddConstraint(
            model_name='attractions',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name_of_attraction'),
        ),
        migrations.AddConstraint(
            model_name='tickettypes',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name_of_type'),
        ),
    ]
