# Generated by Django 5.2.8 on 2025-11-07 15:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gagi_app', '0003_situationstage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attractions',
            old_name='capacity',
            new_name='sourceity',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='birthday',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='hash_password',
            new_name='password_hash',
        ),
        migrations.AddField(
            model_name='attractions',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='attraction_images/', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/', verbose_name='Фотография сотрудника'),
        ),
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users_photos/', verbose_name='Фотография профиля'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='duration_minutes',
            field=models.IntegerField(null=True, verbose_name='Продолжительность (мин)'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='max_height',
            field=models.IntegerField(null=True, verbose_name='Максимальный рост (см)'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='min_age',
            field=models.IntegerField(null=True, verbose_name='Минимальный возраст'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='min_height',
            field=models.IntegerField(null=True, verbose_name='Минимальный рост (см)'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время покупки'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gagi_app.tickettypes', verbose_name='Тип билета'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='valid_until',
            field=models.DateTimeField(verbose_name='Действителен до, null=True, blank=True'),
        ),
    ]
