# Generated by Django 5.2.8 on 2025-11-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gagi_app', '0004_rename_capacity_attractions_sourceity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attractions',
            old_name='sourceity',
            new_name='capacity',
        ),
        migrations.AddField(
            model_name='attractions',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='attractions',
            name='playground_type',
            field=models.CharField(choices=[('small', 'Малая площадка'), ('big', 'Большая площадка')], default='small', max_length=10, verbose_name='Тип площадки'),
        ),
        migrations.AddField(
            model_name='tickettypes',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Продолжительность (мин)'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='max_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальный рост (см)'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='min_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальный возраст'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='min_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальный рост (см)'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Действителен до'),
        ),
    ]
