# Generated by Django 5.2.8 on 2025-11-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gagi_app', '0005_rename_sourceity_attractions_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettypes',
            name='quantity',
            field=models.CharField(default='1 гость', max_length=50, verbose_name='Количество гостей'),
        ),
    ]
