# Generated by Django 5.2.8 on 2025-11-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gagi_app', '0006_tickettypes_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время регистрации'),
        ),
    ]
